name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use a fresh Ubuntu VM for each job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify the Node.js version

      - name: Install dependencies
        run: npm install # Install Node.js package dependencies

      - name: Run tests (if you have them)
        # You would add your test command here, e.g., 'npm test'
        # For this simple app, we can skip it or add a placeholder
        run: echo "No tests configured for this simple app. Add 'npm test' if you have tests."

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Required for building Docker images efficiently

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # GitHub Secret for Docker Hub username
          password: ${{ secrets.DOCKER_TOKEN }}    # GitHub Secret for Docker Hub Access Token/Password

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
                  ashdockertest/node-web-app:latest # Replace with your Docker Hub username and repo name
                  ashdockertest/node-web-app:${{ github.sha }} # Tag with commit SHA for versioning
